"""Rebuild words.js from 'Andy Words.pdf'.

The PDF is a 3-column table (word | level | definition), partly OCR'd from a
scan, so we parse by word position rather than text order: each UL/ML/LL token
starts an entry, the word to its left belongs to it, and definition text to its
right belongs to the nearest entry at or above it. Only LL and ML words are kept.

Requires: pip install pymupdf
Usage:    python3 build_wordbank.py
"""
import json, re, statistics
from pathlib import Path
import pymupdf

HERE = Path(__file__).parent
LEVELS = ('UL', 'ML', 'LL')
POS = r'(noun|verb|adjective|adverb|preposition|conjunction|interjection|pronoun)'
LAST_VOCAB_PAGE = 28  # later pages are a prefix/root table, not vocab

# Hand fixes for OCR noise / layout glitches spotted on review.
FIX_WORD = {'controversia I': 'controversial'}
FIX = {
    'rouse': ('verb', 'to bring out of a state of sleep or inactivity'),
    'cascade': ('noun/verb', 'a waterfall, a graceful descent; or, to flow'),
    'zany': ('adjective', 'whimsical, clownish'),
    'synchronize': ('verb', 'to operate, work, etc., at the same rate and exactly together'),
}


def level_of(tok):
    t = tok.rstrip('.,')
    return t if t in LEVELS else None


def extract(pdf_path):
    entries = []
    doc = pymupdf.open(pdf_path)
    for page in list(doc)[:LAST_VOCAB_PAGE]:
        ws = page.get_text('words')
        foot = [w[1] for w in ws if w[4] in ('Tutoring', 'Services,')]
        if foot:
            ws = [w for w in ws if w[1] < min(foot) - 3]
        lv = [w for w in ws if level_of(w[4])]
        lx = statistics.median(w[0] for w in lv)
        lv = sorted([w for w in lv if abs(w[0] - lx) < 6], key=lambda w: w[1])
        starts = [{'y': w[1], 'level': level_of(w[4]), 'word': [], 'defn': []} for w in lv]
        for w in ws:
            if level_of(w[4]) or w[4] in ('Vocab', 'Word', 'Definition', "'"):
                continue
            if w[2] < lx - 2:
                best = min(starts, key=lambda s: abs(s['y'] - w[1]))
                if abs(best['y'] - w[1]) <= 10:
                    best['word'].append(w)
            elif w[0] > lx + 8:
                above = [s for s in starts if s['y'] <= w[1] + 5]
                if above:
                    above[-1]['defn'].append(w)
        for s in starts:
            word = ' '.join(t[4] for t in sorted(s['word'], key=lambda t: (round(t[1]), t[0])))
            defn = ' '.join(t[4] for t in sorted(s['defn'], key=lambda t: (round(t[1] / 4), t[0])))
            entries.append((word, s['level'], defn))
    return entries


def clean(word, level, defn):
    w = FIX_WORD.get(word)
    if not w:
        toks = [t for t in word.split() if re.fullmatch(r"[a-z][a-z'-]+", t)]
        w = max(toks, key=len)
    if w in FIX:
        return [w, level, *FIX[w]]
    d = re.sub(r'^[I|]\s+', '', defn)
    d = re.sub(r'^-\s+' + POS + r'\s+', r'\1 - ', d)
    d = re.sub(r'\s+', ' ', d).strip()
    m = re.match(POS + r'\s*-\s*(.*)$', d)
    pos, text = (m.group(1), m.group(2)) if m else ('', d)
    return [w, level, pos, text]


def main():
    rows = [clean(*e) for e in extract(HERE / 'Andy Words.pdf')]
    rows = sorted([r for r in rows if r[1] in ('LL', 'ML')], key=lambda r: r[0])
    js = ("// ISEE vocabulary word bank: LL (lower level) and ML (middle level) words\n"
          "// from 'Andy Words.pdf' (UL words excluded). Generated by build_wordbank.py.\n"
          "// Each row: [word, level, part of speech, definition]\n"
          "window.WORD_BANK = " + json.dumps(rows, indent=0) + ";\n")
    (HERE / 'words.js').write_text(js)
    print(f'Wrote {len(rows)} words')


if __name__ == '__main__':
    main()
