// Extra answers to accept for each word, on top of the textbook definition in
// words.js: everyday synonyms and kid-style paraphrases, separated by ";".
// The grader treats each one like another phrase of the definition, so an
// answer matching one of these is "mostly right" and a partial match is
// "somewhat right". Add to this list whenever a fair answer gets marked wrong.
window.EXTRA_ANSWERS = {
  abolish: "get rid of; end; cancel; eliminate; stop; ban",
  abridge: "cut down; make shorter; condense; shorten; summarize",
  abrupt: "suddenly; sudden; quick; unexpected; without warning; blunt",
  abstain: "hold back; refrain; not do; avoid; resist; skip",
  abundant: "lots; plenty; a lot; plentiful; many; tons; more than enough",
  abyss: "hole; pit; deep hole; chasm; void; bottomless",
  acclaim: "praise; applause; approval; honor; cheer",
  accompany: "go with; join; come along; escort; go along with",
  acknowledge: "admit; recognize; accept; notice; agree",
  acute: "sharp; severe; intense; serious; strong",
  adapt: "adjust; change; fit in; get used to; modify",
  adept: "skilled; good at; expert; talented; skillful",
  adhere: "stick; stick to; follow; obey; be loyal",
  adhesive: "glue; tape; sticky; paste",
  adjust: "change; fix; modify; alter; adapt; tweak",
  admire: "look up to; respect; like; appreciate; think highly of; adore",
  adverse: "bad; harmful; negative; unfavorable; opposing",
  affiliation: "connection; association; membership; link; relationship; belong",
  agile: "nimble; quick; flexible; fast; athletic; moves easily",
  ail: "be sick; ill; unwell; hurt; trouble",
  aimless: "no purpose; pointless; random; no goal; wandering; directionless",
  akin: "related; similar; like; alike; connected",
  allege: "claim; say; accuse; state without proof",
  aloof: "distant; unfriendly; cold; standoffish; keeps to themselves; apart",
  ambiance: "mood; atmosphere; feeling; vibe; setting",
  ambiguous: "unclear; vague; confusing; uncertain; more than one meaning",
  ambitious: "determined; driven; motivated; wants to succeed; goal oriented; eager",
  ambivalent: "mixed feelings; unsure; undecided; uncertain; torn",
  amiable: "friendly; nice; kind; pleasant; likeable",
  amorphous: "shapeless; no shape; formless; blob",
  analyze: "examine; study; inspect; look closely; break down; evaluate",
  anguish: "pain; suffering; misery; agony; distress; sorrow",
  annex: "add; attach; take over; addition; extension",
  annul: "cancel; undo; void; erase; nullify",
  anomalous: "unusual; abnormal; odd; strange; out of place; weird",
  antidote: "cure; remedy; treatment; medicine; fix",
  appropriate: "suitable; proper; fitting; right; correct; take",
  approximate: "estimate; about; close; rough; near; guess",
  arbitrary: "random; by chance; no reason; personal choice; unpredictable",
  arid: "dry; desert; no water; parched",
  assert: "state; declare; claim; insist; say firmly",
  assess: "evaluate; judge; measure; check; rate; test",
  astonish: "amaze; surprise; shock; stun; astound",
  audible: "can be heard; hearable; loud enough; clear",
  authentic: "real; genuine; true; original; legit",
  authoritative: "in charge; commanding; official; reliable; bossy; powerful",
  authorize: "allow; permit; approve; give permission; let",
  barrage: "flood; rush; attack; storm; bombardment; lots at once",
  barren: "empty; bare; lifeless; infertile; dry; desolate",
  barrier: "wall; block; obstacle; fence; blockade; barricade",
  bashful: "shy; timid; embarrassed; nervous",
  behold: "see; look; observe; watch; view",
  bemoan: "complain; whine; moan; mourn; regret; lament",
  beneficial: "helpful; good; useful; good for you; advantageous",
  benevolence: "kindness; goodness; generosity; charity",
  benign: "harmless; gentle; kind; safe; not harmful",
  bewilder: "confuse; puzzle; baffle; perplex",
  biased: "unfair; one sided; prejudiced; partial; favoring",
  blatant: "obvious; open; shameless; brazen; clear",
  blunt: "direct; straightforward; honest; to the point; dull",
  boisterous: "loud; noisy; rowdy; wild; energetic",
  brash: "bold; rude; reckless; cocky; tactless",
  brazen: "shameless; bold; daring; blatant",
  brief: "short; quick; fast; concise",
  brittle: "fragile; breakable; easily broken; delicate; breaks easily",
  browbeat: "bully; intimidate; pressure; boss around",
  calamity: "disaster; catastrophe; tragedy; misfortune",
  candid: "honest; frank; truthful; direct; straightforward; open",
  caress: "pet; stroke; touch gently; hug; cuddle",
  cascade: "waterfall; flow; pour; fall; tumble",
  cater: "serve; provide; supply; take care of; please",
  cautious: "careful; wary; watchful; alert",
  chronic: "constant; ongoing; repeated; long lasting; always; continuous; recurring; happens a lot",
  chronicle: "record; history; account; story; diary",
  civility: "politeness; manners; courtesy; respect",
  clash: "conflict; fight; collide; argue; clash",
  coarse: "rough; harsh; bumpy; crude; gritty",
  coerce: "force; pressure; make; bully",
  collide: "crash; hit; bump; smash",
  colossal: "huge; giant; enormous; massive; gigantic; big",
  commendable: "praiseworthy; admirable; good; worthy",
  commonplace: "ordinary; common; normal; everyday; usual; boring",
  compel: "force; make; push; require; pressure",
  competent: "capable; skilled; able; qualified; good enough",
  composure: "calmness; calm; self control; poise; cool",
  comprehensive: "complete; thorough; full; total; everything",
  conceal: "hide; cover; disguise; mask",
  concise: "short; brief; to the point; clear",
  condemn: "blame; criticize; sentence; convict; disapprove",
  condescending: "snobby; superior; looking down on; patronizing; stuck up; arrogant",
  condone: "allow; forgive; overlook; excuse; accept",
  confide: "trust; tell secrets; share; open up",
  confine: "restrict; limit; enclose; trap; lock up",
  conform: "follow rules; obey; fit in; comply; go along",
  confound: "confuse; puzzle; baffle; bewilder",
  contemplation: "thinking; thought; reflection; consideration; pondering",
  content: "happy; satisfied; pleased; okay",
  contradict: "deny; disagree; oppose; go against",
  controversial: "debatable; disputed; argued; touchy; divisive",
  conventional: "traditional; normal; usual; ordinary; standard",
  conversation: "talk; chat; discussion; dialogue",
  convey: "communicate; tell; express; share; carry",
  corroborate: "confirm; support; back up; prove; verify",
  counsel: "advise; advice; guide; help; recommend",
  counterfeit: "fake; forged; false; phony; copy",
  credible: "believable; trustworthy; reliable; realistic",
  creed: "belief; beliefs; faith; principles; religion",
  crucial: "important; necessary; essential; critical; vital; key",
  cunning: "sly; sneaky; clever; crafty; tricky; smart",
  curb: "restrain; limit; control; hold back; check",
  dawdle: "waste time; dilly dally; delay; linger; lag; slow",
  debate: "argue; discuss; argument; discussion",
  debilitating: "weakening; harmful; disabling; exhausting",
  debris: "rubble; trash; wreckage; remains; junk; garbage",
  debt: "money owed; owe; loan",
  deceive: "trick; lie; fool; mislead; cheat",
  decline: "say no; refuse; turn down; reject; decrease",
  decrease: "lessen; reduce; go down; shrink; lower",
  defensive: "protective; guarded; sensitive",
  defiant: "disobedient; rebellious; resistant; bold",
  deficient: "lacking; missing; not enough; insufficient; inadequate",
  deft: "skillful; skilled; good at something; nimble; handy",
  dejection: "sadness; depression; low spirits; gloom; sorrow",
  deliberate: "on purpose; intentional; planned; careful",
  denial: "refusal; disbelief; rejection; not accepting",
  deny: "say no; refuse; reject; disagree; say not true",
  depict: "show; portray; describe; illustrate; draw",
  desperate: "hopeless; urgent; in need; frantic; anxious",
  detest: "hate; despise; loathe; dislike",
  detrimental: "harmful; damaging; bad; destructive",
  deviate: "stray; wander; depart; turn away; differ",
  devotion: "dedication; loyalty; love; commitment",
  differentiate: "distinguish; tell apart; separate; tell difference",
  difficult: "hard; tough; challenging; tricky",
  dignity: "self respect; pride; honor; respect",
  dilute: "water down; weaken; thin; weaker",
  discreet: "careful; quiet; secret; private; subtle",
  dismayed: "upset; disappointed; discouraged; worried; shocked",
  dispel: "get rid of; drive away; scatter; banish; eliminate",
  disperse: "scatter; spread out; separate; break up",
  dispute: "argue; disagree; fight; argument; debate",
  dissect: "cut apart; cut up; analyze; take apart",
  distasteful: "unpleasant; offensive; gross; disgusting",
  distinguished: "famous; important; respected; honored; well known",
  distort: "twist; bend; warp; misrepresent; change",
  distrust: "doubt; suspect; not trust; suspicion",
  diversity: "variety; difference; mix; range; different",
  divine: "godly; holy; heavenly; sacred",
  docile: "calm; gentle; tame; obedient; easy to control",
  domestic: "household; home; family; tame",
  dominate: "rule; control; govern; take over; overpower",
  donate: "give; contribute; gift; charity",
  dormant: "inactive; sleeping; asleep; resting; quiet",
  drastic: "extreme; severe; harsh; dramatic; big",
  dread: "fear; terror; scared; afraid",
  dregs: "leftovers; scraps; worst part; remains",
  drench: "soak; wet; drown",
  dubious: "doubtful; unsure; suspicious; questionable; uncertain",
  duration: "length; time; period; how long",
  eager: "excited; keen; ready; enthusiastic; anxious",
  economize: "save; save money; cut back; budget; conserve",
  edit: "revise; correct; fix; change",
  elation: "joy; happiness; delight; excitement; thrilled",
  elongate: "lengthen; stretch; extend; make longer",
  eloquent: "well spoken; expressive; fluent; good speaker",
  embodying: "representing; showing; personifying; symbolizing",
  emphasis: "importance; stress; focus; attention",
  enclose: "surround; fence in; close in; contain",
  encumber: "burden; weigh down; hinder; load",
  endeavor: "attempt; try; effort; strive",
  engage: "attract; involve; hold attention; participate; interest",
  entrust: "trust; give responsibility; hand over; assign",
  envelop: "surround; wrap; cover; engulf",
  envy: "jealous; jealousy; want what others have; covet",
  equitable: "fair; just; equal; reasonable",
  equity: "fairness; justice; equality",
  equivalent: "equal; same; identical; matching",
  erode: "wear away; wear down; eat away; decay",
  erratic: "unpredictable; random; inconsistent; strange; irregular",
  eternal: "forever; endless; everlasting; permanent; never ending",
  euphemism: "nicer way to say; softer word; polite term",
  evacuate: "leave; empty; vacate; get out; escape",
  evade: "avoid; escape; dodge; get away",
  excavate: "dig; dig up; unearth",
  excel: "do well; be great; succeed; outdo",
  exclude: "leave out; keep out; reject; omit; ban",
  exemplify: "show; demonstrate; be an example; illustrate",
  exile: "banish; kick out; send away; expel",
  exquisite: "beautiful; delicate; elegant; fine; gorgeous",
  extend: "stretch; lengthen; expand; make longer",
  extinct: "dead; gone; died out; no longer exists",
  extract: "remove; pull out; take out; draw out",
  extravagant: "fancy; excessive; luxurious; over the top; expensive; wasteful",
  exuberant: "excited; enthusiastic; lively; joyful; energetic",
  facet: "aspect; side; part; feature",
  falter: "stumble; hesitate; waver; slip; mess up",
  fanatic: "extremist; zealot; obsessed; superfan; enthusiast",
  fathom: "understand; comprehend; grasp; figure out; measure depth",
  fatigue: "tiredness; exhaustion; weariness",
  favorable: "good; positive; helpful; approving",
  feasible: "possible; doable; achievable; realistic",
  feeble: "weak; frail; fragile; powerless",
  feisty: "spirited; lively; energetic; bold; spunky",
  fickle: "changing; unreliable; unpredictable; changes mind",
  fission: "splitting; division; breaking apart",
  fissure: "crack; gap; split; opening; crevice",
  flaccid: "limp; floppy; soft; saggy",
  flatter: "compliment; praise; sweet talk",
  fleeting: "brief; short; quick; passing; temporary",
  flourish: "thrive; grow; prosper; succeed; bloom",
  foolhardy: "reckless; rash; foolish; dumb; risky",
  foresee: "predict; anticipate; expect; see coming",
  foreshorten: "shorten; reduce; abridge; cut",
  forge: "make; shape; form; fake; copy",
  forlorn: "lonely; sad; abandoned; hopeless",
  formulate: "plan; create; devise; develop; express",
  fortunate: "lucky; blessed",
  foster: "encourage; promote; nurture; raise; support; care for",
  fragile: "breakable; delicate; weak; easily broken",
  frank: "honest; direct; straightforward; straight forward; open; blunt; truthful; says what they think; candid",
  frantic: "panicked; wild; frenzied; desperate; hectic",
  frightful: "scary; terrible; awful; horrible; dreadful",
  frugal: "cheap; thrifty; saves money; careful with money; stingy",
  fruitless: "useless; pointless; unsuccessful; failed; vain",
  fundamental: "basic; essential; necessary; important; core",
  furious: "angry; mad; enraged; livid; raging",
  fuse: "join; combine; merge; melt together; wick",
  fusion: "joining; merging; combination; blend",
  genuine: "real; authentic; true; sincere; honest",
  glean: "gather; collect; pick up; learn",
  glint: "flash; sparkle; gleam; shine; glimmer",
  glisten: "shine; sparkle; glimmer; glitter; gleam",
  glitch: "bug; error; problem; defect; malfunction",
  graceful: "elegant; smooth; flowing; beautiful",
  gratify: "please; satisfy; delight",
  grave: "serious; solemn; important; severe",
  grievance: "complaint; problem; grudge; objection",
  guarantee: "promise; assurance; warranty; pledge",
  gullible: "easily fooled; naive; trusting; believes anything",
  habitat: "home; environment; where an animal lives; natural home",
  habitual: "regular; usual; routine; customary; habit",
  haphazard: "random; careless; messy; disorganized; sloppy",
  hardship: "difficulty; struggle; trouble; suffering; hard time",
  hardy: "strong; tough; sturdy; healthy",
  hasten: "hurry; rush; speed up; quicken",
  haughty: "arrogant; proud; snobby; stuck up; conceited",
  hazard: "danger; risk; threat",
  heap: "pile; stack; mound; lot",
  hectic: "busy; chaotic; crazy; frantic; rushed",
  herald: "messenger; announcer; announce",
  hesitate: "pause; wait; delay; hold back; be unsure",
  hinder: "slow down; block; delay; get in the way; obstruct",
  hoard: "stockpile; collect; store up; save up; stash",
  hoax: "trick; prank; fake; scam; joke",
  hoist: "lift; raise; pull up",
  homely: "plain; ugly; unattractive",
  hoodwink: "trick; fool; deceive; con",
  hovel: "shack; hut; shed",
  hubris: "pride; arrogance; overconfidence; ego",
  hypothesis: "guess; theory; prediction; idea",
  idealism: "high standards; dreams; optimism; ideals",
  idiosyncrasy: "quirk; habit; trait; oddity; peculiarity",
  ignorant: "uneducated; unaware; clueless; doesn't know",
  illuminate: "light up; brighten; light; explain",
  illustrate: "draw; show; explain; picture; demonstrate",
  immaculate: "spotless; very clean; perfect; pristine; neat",
  immediate: "instant; right away; now; immediately",
  immunity: "protection; resistance; not get sick",
  impasse: "deadlock; standstill; dead end; stuck",
  impede: "block; slow down; hinder; obstruct; get in the way",
  imply: "hint; suggest; mean",
  impoverish: "make poor; drain; exhaust; weaken",
  impulsive: "spontaneous; rash; hasty; without thinking",
  inane: "silly; stupid; pointless; senseless",
  incentive: "reward; motivation; reason; encouragement",
  incident: "event; happening; occurrence; situation",
  incision: "cut; gash; slit",
  incompetent: "unable; unskilled; unqualified; bad at",
  indifferent: "uncaring; unconcerned; don't care; neutral",
  infiltrate: "sneak in; get in; filter; penetrate; enter secretly",
  ingenious: "clever; brilliant; inventive; creative; smart",
  inhabit: "live in; occupy; reside; dwell",
  initial: "first; beginning; starting; early",
  initiate: "start; begin; launch",
  innate: "natural; inborn; born with",
  innovate: "invent; create; new idea; come up with",
  inquiry: "question; investigation; asking",
  inscribe: "write; carve; engrave; etch",
  inscrutable: "mysterious; confusing; hard to understand",
  insight: "understanding; awareness; wisdom",
  instigate: "start; provoke; cause; trigger",
  intangible: "untouchable; can't be touched; abstract",
  integrate: "combine; include; join; merge; mix",
  integrity: "honesty; honor; morals; good character",
  intermission: "break; pause; recess; halftime",
  intricate: "complicated; complex; detailed",
  invoke: "call on; summon; appeal to; ask for",
  jeer: "mock; tease; make fun of; taunt; boo",
  justify: "explain; defend; prove right; excuse",
  keen: "sharp; eager; excited; smart",
  kinetic: "moving; motion; active; energetic",
  languid: "weak; tired; lazy; sluggish; slow",
  lament: "mourn; grieve; cry; be sad; regret",
  legislate: "make laws; pass laws",
  lethal: "deadly; fatal; killing; dangerous",
  liberate: "free; release; let go; set free",
  limber: "flexible; bendy; nimble",
  linger: "stay; wait; hang around; remain; dawdle",
  listless: "tired; sluggish; bored; lazy",
  loathe: "hate; despise; detest; dislike",
  lodging: "housing; room; shelter; place to stay; hotel",
  magnify: "enlarge; make bigger; zoom; enhance",
  malignant: "harmful; dangerous; evil; deadly; cancerous",
  mar: "spoil; ruin; damage; scratch",
  meager: "small; little; scanty; not enough; skimpy",
  meander: "wander; roam; ramble; drift",
  meddle: "interfere; butt in; snoop",
  meditate: "think; reflect; ponder; relax",
  medley: "mix; mixture; assortment; blend",
  meek: "quiet; humble; shy; gentle; timid",
  memento: "souvenir; keepsake; reminder",
  merciless: "cruel; heartless; ruthless; mean",
  merge: "combine; join; unite; blend; put together",
  meticulous: "careful; thorough; precise; detailed; picky",
  mischievous: "naughty; playful; troublesome; sneaky",
  moderate: "medium; average; mild; reasonable; middle",
  modify: "change; alter; adjust",
  molten: "melted; liquid; hot",
  momentous: "important; significant; huge; historic",
  mope: "sulk; brood; be sad; pout",
  muddle: "mix up; mess up; confuse; jumble",
  mundane: "boring; ordinary; everyday; dull",
  mute: "silent; quiet; speechless",
  negate: "cancel; undo; deny",
  noncommittal: "undecided; vague; neutral; won't decide",
  nostalgic: "missing the past; memories; sentimental; homesick",
  notorious: "infamous; famous for something bad; known for bad",
  novice: "beginner; newbie; rookie; amateur",
  noxious: "harmful; toxic; poisonous; dangerous",
  null: "nothing; zero; invalid",
  obedient: "well behaved; follows rules; listens; compliant",
  objective: "goal; aim; purpose; target; fair",
  obscure: "hidden; unclear; unknown; vague; covered",
  obstruct: "block; hinder; stop; get in the way",
  occupation: "job; career; work; profession",
  occupy: "take up; fill; live in; inhabit",
  ominous: "threatening; menacing; scary; bad sign",
  omit: "leave out; skip; exclude; remove",
  optimistic: "positive; hopeful; confident; cheerful",
  overbearing: "bossy; controlling; domineering; arrogant",
  overt: "open; obvious; clear; public; not hidden",
  overwhelm: "overpower; flood; crush; too much",
  pacify: "calm; soothe; calm down; make peace",
  pact: "agreement; deal; treaty; promise",
  palpable: "obvious; noticeable; tangible; real",
  paltry: "small; tiny; worthless; measly",
  parody: "spoof; imitation; mockery; joke",
  partial: "incomplete; part; some; biased",
  particle: "bit; piece; speck; tiny piece",
  partisan: "biased; one sided; loyal; supporter",
  patron: "customer; client; supporter; sponsor",
  pedestrian: "walker; person walking; ordinary; boring",
  permeate: "spread through; soak; fill; seep",
  perplexed: "confused; puzzled; baffled",
  persecute: "harass; bully; mistreat; torment; oppress",
  personify: "give human qualities; represent; embody",
  perspective: "point of view; opinion; viewpoint; outlook",
  pervasive: "widespread; everywhere; common",
  pessimistic: "negative; gloomy; hopeless; doubtful",
  philanthropy: "charity; giving; generosity; donation",
  pigment: "color; dye; paint",
  pilfer: "steal; take; swipe; rob",
  pinnacle: "peak; top; height; summit; best",
  pious: "religious; holy; devout",
  placate: "calm; soothe; pacify; calm down; please",
  plausible: "believable; possible; reasonable; likely",
  plight: "problem; trouble; predicament; bad situation",
  pompous: "arrogant; full of yourself; showy; snobby",
  porous: "full of holes; absorbent; leaky",
  practical: "useful; sensible; realistic; handy",
  precede: "come before; go before; lead",
  preclude: "prevent; rule out; stop; block",
  precocious: "advanced; mature; gifted; smart for age",
  prediction: "forecast; guess; prophecy",
  prejudiced: "biased; unfair; judging",
  preserve: "protect; save; keep; maintain",
  presume: "assume; guess; suppose; believe",
  pretentious: "showy; snobby; pompous; fake; stuck up",
  priceless: "valuable; precious; invaluable; worth a lot",
  pristine: "clean; spotless; perfect; untouched; brand new",
  probable: "likely; expected; possible",
  proclaim: "announce; declare; state",
  profane: "disrespectful; rude; vulgar; offensive; swear",
  prolific: "productive; fruitful; creates a lot",
  prominent: "important; famous; noticeable; obvious",
  prone: "likely; inclined; tends to; lying face down",
  prophecy: "prediction; forecast; vision",
  prototype: "model; first version; draft; test version",
  provoke: "anger; annoy; irritate; tease; cause",
  pugnacious: "aggressive; combative; ready to fight; hostile",
  pungent: "strong smell; stinky; sharp",
  quake: "shake; tremble; shiver",
  quash: "crush; suppress; stop; end; squash",
  quell: "stop; calm; end; put down; quiet",
  quiver: "shake; tremble; shiver; arrow holder",
  rash: "hasty; reckless; careless; impulsive",
  ratify: "approve; confirm; sign; agree",
  ravenous: "starving; very hungry; famished",
  react: "respond; answer",
  recoil: "pull back; flinch; jump back",
  reflex: "automatic; reaction; instinct",
  refute: "disprove; deny; prove wrong",
  relentless: "nonstop; unstoppable; persistent; constant; harsh",
  reluctant: "unwilling; hesitant; not wanting to",
  reminisce: "remember; recall; look back",
  remote: "far away; distant; isolated",
  renaissance: "rebirth; revival; renewal",
  rendezvous: "meeting; date; meetup",
  rendition: "version; performance; interpretation",
  renounce: "give up; reject; quit",
  renown: "fame; reputation; famous",
  replenish: "refill; restock; reload",
  repress: "hold back; hold in; hide; suppress",
  reprimand: "scold; criticize; tell off",
  reproach: "blame; criticize; scold",
  residual: "leftover; remaining; lingering",
  resolve: "decide; determine; fix; solve",
  restore: "fix; repair; bring back; renew",
  restraint: "self control; holding back; control; limit",
  retort: "reply; comeback; answer back",
  revere: "respect; admire; worship; honor",
  revert: "go back; return; turn back",
  rickety: "shaky; wobbly; unstable; falling apart",
  righteous: "good; moral; right; just; virtuous",
  rigid: "stiff; hard; firm; strict",
  robust: "strong; sturdy; healthy; tough",
  rouse: "wake up; awaken; stir; excite",
  rue: "regret; be sorry; feel sorry",
  ruminate: "think; ponder; reflect; dwell",
  rustic: "country; rural; simple; farm",
  ruthless: "cruel; merciless; heartless",
  sacred: "holy; religious; blessed",
  sage: "wise person; wise; scholar; expert",
  salvage: "save; rescue; recover",
  satire: "parody; mockery; spoof",
  savor: "enjoy; relish; appreciate",
  scant: "little; not enough; barely enough",
  scarce: "rare; few; lacking; not enough",
  scrutinize: "examine; inspect; study closely; check",
  scurry: "hurry; rush; scamper; dash",
  seclude: "isolate; hide; separate",
  secure: "safe; protected; locked",
  sedate: "calm; tranquilize; put to sleep",
  seize: "grab; take; capture; snatch",
  seldom: "rarely; not often; hardly ever",
  serene: "calm; peaceful; tranquil; quiet",
  severity: "seriousness; harshness; intensity",
  shrewd: "clever; smart; sharp; sly",
  simulate: "fake; pretend; imitate; copy",
  sincere: "honest; genuine; real; truthful",
  sinister: "evil; threatening; scary; menacing",
  solemn: "serious; grave; somber",
  solitary: "alone; lonely; single",
  somber: "serious; dark; gloomy; sad",
  soothe: "calm; comfort; relax",
  specter: "ghost; phantom; spirit; threat",
  spontaneous: "unplanned; sudden; impulsive",
  stagnate: "stop; still; stale; not change",
  stature: "height; size; status",
  steadfast: "loyal; firm; steady; determined",
  stifle: "suppress; hold back; smother",
  subjective: "opinion; personal; biased",
  subside: "calm down; decrease; lessen; die down",
  subtle: "slight; faint; delicate; not obvious",
  succinct: "short; brief; concise; to the point",
  sullen: "grumpy; sulky; moody; gloomy",
  sullied: "dirty; stained; soiled",
  surly: "rude; grumpy; unfriendly",
  surrogate: "substitute; replacement; stand in",
  sympathize: "feel for; understand; pity",
  synchronize: "coordinate; match; align; together",
  tact: "politeness; sensitivity; diplomacy",
  tangible: "touchable; real; concrete",
  taper: "narrow; thin out; decrease",
  task: "job; chore; duty; assignment",
  tattered: "torn; ragged; worn out",
  taunt: "tease; mock; make fun of",
  temperament: "personality; mood; nature; attitude",
  terse: "short; brief; curt; blunt",
  thorough: "careful; complete; detailed",
  thrive: "do well; flourish; succeed; grow",
  thwart: "stop; block; prevent; foil",
  timid: "shy; scared; nervous; fearful; afraid",
  tiresome: "boring; tiring; annoying; dull",
  toil: "work hard; labor; hard work",
  torment: "torture; pain; suffering; bother",
  treacherous: "dangerous; risky; untrustworthy",
  trifle: "small thing; trinket; little",
  trite: "overused; unoriginal; cliche",
  truce: "ceasefire; peace; agreement",
  ultimate: "final; last; best; greatest",
  uncouth: "rude; crude; clumsy; awkward",
  undermine: "weaken; sabotage; damage",
  unique: "one of a kind; special; different",
  unruly: "wild; rowdy; disorderly",
  unusual: "strange; odd; different; rare",
  uproot: "pull up; remove; dig up",
  utilitarian: "useful; practical; functional",
  utilize: "use; employ; apply",
  vacillate: "waver; go back and forth; hesitate",
  vanity: "pride; conceit; self love; ego",
  variable: "changing; changeable; varying",
  vast: "huge; big; large; enormous; wide",
  vend: "sell",
  versatile: "flexible; adaptable; many uses",
  viewpoint: "opinion; perspective; point of view",
  vigilant: "watchful; alert; careful",
  vigorous: "energetic; strong; powerful",
  visible: "seen; obvious; noticeable",
  vivacious: "lively; energetic; bubbly",
  vivid: "bright; colorful; clear; detailed",
  warble: "sing; trill; chirp",
  weary: "tired; exhausted; worn out",
  wily: "sly; sneaky; crafty; tricky",
  woeful: "sad; miserable; terrible",
  worthy: "deserving; good enough; worthwhile",
  wrath: "anger; rage; fury",
  writhe: "twist; squirm; wriggle",
  yield: "give up; surrender; give way",
  zany: "silly; goofy; crazy; wacky; funny",
};
