// ISEE vocabulary word bank: LL (lower level) and ML (middle level) words
// from 'Andy Words.pdf' (UL words excluded). Generated by build_wordbank.py.
// Each row: [word, level, part of speech, definition]
window.WORD_BANK = [
[
"abolish",
"LL",
"verb",
"to do away with, put an end to"
],
[
"abridge",
"ML",
"verb",
"to shorten"
],
[
"abrupt",
"LL",
"adjective",
"sudden or unexpected"
],
[
"abstain",
"ML",
"verb",
"to hold oneself back voluntarily"
],
[
"abundant",
"ML",
"adjective",
"plentiful, in great supply"
],
[
"abyss",
"ML",
"noun",
"a deep pit"
],
[
"acclaim",
"ML",
"noun",
"praise"
],
[
"accompany",
"ML",
"verb",
"to go along or in company with, to join in action"
],
[
"acknowledge",
"ML",
"verb",
"to admit or recognize"
],
[
"acute",
"ML",
"adjective",
"sharp or severe in effect"
],
[
"adapt",
"LL",
"verb",
"to make suitable for new conditions"
],
[
"adept",
"ML",
"adjective",
"very skilled"
],
[
"adhere",
"ML",
"verb",
"to be devoted in support or allegiance; or, to stick to something"
],
[
"adhesive",
"LL",
"noun",
"glue, something sticky"
],
[
"adjust",
"ML",
"verb",
"to change (something) so that it fits, corresponds, or conforms"
],
[
"admire",
"LL",
"verb",
"to regard with wonder or pride"
],
[
"adverse",
"ML",
"adjective",
"unfavorable"
],
[
"affiliation",
"ML",
"noun",
"in association with something"
],
[
"agile",
"ML",
"adjective",
"quick, lithe, flexible"
],
[
"ail",
"ML",
"verb",
"to be unwell, ill"
],
[
"aimless",
"ML",
"adjective",
"without aim or purpose"
],
[
"akin",
"ML",
"adjective",
"related to"
],
[
"allege",
"ML",
"verb",
"to declare something to be true"
],
[
"aloof",
"ML",
"adjective",
"keeping a distance"
],
[
"ambiance",
"ML",
"noun",
"the mood, character, quality, tone, atmosphere, etc., particularly of an environment"
],
[
"ambiguous",
"ML",
"adjective",
"unclear, open to interpretation"
],
[
"ambitious",
"ML",
"adjective",
"eagerly desirous of achieving or obtaining success, power, wealth, a specific goal, etc."
],
[
"ambivalent",
"ML",
"adjective",
"having opposing or mixed feelings"
],
[
"amiable",
"ML",
"adjective",
"friendly"
],
[
"amorphous",
"ML",
"adjective",
"without definite shape"
],
[
"analyze",
"LL",
"verb",
"to examine critically"
],
[
"anguish",
"ML",
"noun",
"excruciating pain or distress"
],
[
"annex",
"ML",
"noun",
"an addition; or verb - to attach or add"
],
[
"annul",
"ML",
"verb",
"to make void or null, abolish, cancel, invalidate"
],
[
"anomalous",
"ML",
"adjective",
"not fitting into a common or familiar type, classification, or pattern; unusual"
],
[
"antidote",
"ML",
"noun",
"a medicine or other remedy for counteracting the effects of poison, disease, etc."
],
[
"appropriate",
"ML",
"adjective",
"suitable or fitting for a particular purpose, person, occasion: or, verb - to set apart, authorize, or legislate for some specific purpose or use"
],
[
"approximate",
"LL",
"adjective",
"estimated, the almost exact amount; or, verb - to estimate"
],
[
"arbitrary",
"ML",
"adjective",
"subject to judgment"
],
[
"arid",
"ML",
"adjective",
"dry (usually referring to land)"
],
[
"assert",
"ML",
"verb",
"to state firmly, to defend"
],
[
"assess",
"LL",
"verb",
"to evaluate something"
],
[
"astonish",
"LL",
"verb",
"to create wonder, to amaze"
],
[
"audible",
"LL",
"adjective",
"able to be heard"
],
[
"authentic",
"LL",
"adjective",
"genuine"
],
[
"authoritative",
"LL",
"adjective",
"having authority, being in charge"
],
[
"authorize",
"LL",
"verb",
"to give authority or official power to"
],
[
"barrage",
"ML",
"noun",
"a flood, a sudden rush"
],
[
"barren",
"ML",
"adjective",
"empty, infertile"
],
[
"barrier",
"LL",
"noun",
"anything built to prevent passage"
],
[
"bashful",
"ML",
"adjective",
"easily embarrassed, shy, timid"
],
[
"behold",
"ML",
"verb",
"to observe, look at, see"
],
[
"bemoan",
"ML",
"verb",
"to express distress"
],
[
"beneficial",
"ML",
"adjective",
"advantageous, helpful"
],
[
"benevolence",
"ML",
"noun",
"goodness"
],
[
"benign",
"ML",
"adjective",
"harmless"
],
[
"bewilder",
"ML",
"verb",
"to amaze, confuse"
],
[
"biased",
"ML",
"adjective",
"favoring one side over another"
],
[
"blatant",
"ML",
"adjective",
"flagrant, brazen"
],
[
"blunt",
"LL",
"adjective",
"short, to the point"
],
[
"boisterous",
"ML",
"adjective",
"rough and noisy, noisily jolly or rowdy, clamorous, unrestrained"
],
[
"brash",
"ML",
"adjective",
"bold, tactless, rude"
],
[
"brazen",
"ML",
"adjective",
"shameless"
],
[
"brief",
"LL",
"adjective",
"lasting or taking a short time, of short duration"
],
[
"brittle",
"LL",
"adjective",
"easy to break"
],
[
"browbeat",
"ML",
"verb",
"to intimidate"
],
[
"calamity",
"ML",
"noun",
"a great misfortune or disaster"
],
[
"candid",
"ML",
"adjective",
"sincere, frank"
],
[
"caress",
"ML",
"verb",
"to touch or pat gently to show affection"
],
[
"cascade",
"LL",
"noun/verb",
"a waterfall, a graceful descent; or, to flow"
],
[
"cater",
"LL",
"verb",
"to attend to"
],
[
"cautious",
"LL",
"adjective",
"careful"
],
[
"chronic",
"ML",
"adjective",
"recurring, constant"
],
[
"chronicle",
"LL",
"noun",
"a record of events, a history"
],
[
"civility",
"ML",
"noun",
"courtesy, politeness"
],
[
"clash",
"ML",
"verb",
"to come together or collide, to conflict, to disagree"
],
[
"coarse",
"ML",
"adjective",
"lacking in fineness or delicacy of texture, structure, etc"
],
[
"coerce",
"ML",
"verb",
"to compel, to persuade"
],
[
"collide",
"LL",
"verb",
"to come into violent contact or crash"
],
[
"colossal",
"ML",
"adjective",
"extraordinarily great in size, extent, or degree"
],
[
"commendable",
"ML",
"adjective",
"worthy of praise"
],
[
"commonplace",
"LL",
"adjective",
"ordinary, undistinguished or uninteresting; without individuality"
],
[
"compel",
"ML",
"verb",
"to force, to drive"
],
[
"competent",
"ML",
"adjective",
"having sufficient skill, knowledge"
],
[
"composure",
"ML",
"noun",
"having control, calmness, tranquility"
],
[
"comprehensive",
"ML",
"adjective",
"covering a wide range of information"
],
[
"conceal",
"LL",
"verb",
"to cover up, to disguise"
],
[
"concise",
"ML",
"adjective",
"short, clear"
],
[
"condemn",
"ML",
"verb",
"to pronounce to be guilty"
],
[
"condescending",
"ML",
"adjective",
"showing superiority in a patronizing fashion"
],
[
"condone",
"ML",
"verb",
"to forgive or disregard an offense"
],
[
"confide",
"ML",
"verb",
"to impart secrets trustfully; discuss private matters or problems"
],
[
"confine",
"LL",
"verb",
"to enclose within boundaries"
],
[
"conform",
"LL",
"verb",
"to comply to rules and restrictions"
],
[
"confound",
"ML",
"verb",
"to perplex, bewilder"
],
[
"contemplation",
"ML",
"noun",
"a consideration of a new idea or belief"
],
[
"content",
"LL",
"adjective",
"happy, adjusted"
],
[
"contradict",
"ML",
"verb",
"to deny, to object"
],
[
"controversial",
"LL",
"adjective",
"something public disputed or debated"
],
[
"conventional",
"ML",
"adjective",
"traditional"
],
[
"conversation",
"ML",
"noun",
"oral communication between people"
],
[
"convey",
"LL",
"verb",
"to communicate, impart, make known"
],
[
"corroborate",
"ML",
"verb",
"to make more certain, confirm"
],
[
"counsel",
"ML",
"verb",
"to advise"
],
[
"counterfeit",
"ML",
"adjective",
"made falsely to deceive"
],
[
"credible",
"ML",
"adjective",
"something capable of being believed, trusted"
],
[
"creed",
"ML",
"noun",
"a doctrine or formula, system of belief"
],
[
"crucial",
"LL",
"adjective",
"necessary"
],
[
"cunning",
"LL",
"adjective",
"sly, witty, often smart in the form of thievery or deception"
],
[
"curb",
"LL",
"noun",
"a restraint; or, verb - to restrain or control"
],
[
"dawdle",
"LL",
"verb",
"to idle, to waste time"
],
[
"debate",
"LL",
"noun",
"a discussion with opposing opinions; or, verb - to oppose something"
],
[
"debilitating",
"ML",
"adjective",
"weakening, harmful"
],
[
"debris",
"ML",
"noun",
"the remains of anything broken down or destroyed, ruins, rubble"
],
[
"debt",
"LL",
"noun",
"something owed, something to be paid back or returned"
],
[
"deceive",
"LL",
"verb",
"to mislead, delude"
],
[
"decline",
"LL",
"verb",
"to turn down an offer"
],
[
"decrease",
"ML",
"verb",
"to diminish or lessen in extent, quantity, strength, power"
],
[
"defensive",
"LL",
"adjective",
"protective"
],
[
"defiant",
"ML",
"adjective",
"bold, resistant"
],
[
"deficient",
"ML",
"adjective",
"lacking an essential part"
],
[
"deft",
"ML",
"adjective",
"skillful"
],
[
"dejection",
"ML",
"noun",
"having low spirits"
],
[
"deliberate",
"LL",
"adjective",
"intentional"
],
[
"denial",
"LL",
"noun",
"disbelief in the existence or reality of a thing"
],
[
"deny",
"ML",
"verb",
"to state that (something declared or believed to be true) is not true"
],
[
"depict",
"ML",
"verb",
"to represent, to portray"
],
[
"desperate",
"ML",
"adjective",
"having an urgent need, desire"
],
[
"detest",
"LL",
"verb",
"to hate"
],
[
"detrimental",
"ML",
"adjective",
"damaging, harmful"
],
[
"deviate",
"ML",
"verb",
"to turn away from a path or course"
],
[
"devotion",
"LL",
"noun",
"dedication"
],
[
"differentiate",
"ML",
"verb",
"to mark differently, to distinguish"
],
[
"difficult",
"LL",
"adjective",
"not easily or readily done; requiring much labor or skill"
],
[
"dignity",
"LL",
"noun",
"self-respect, integrity"
],
[
"dilute",
"ML",
"verb",
"to make thinner, fainter in color"
],
[
"discreet",
"ML",
"adjective",
"prudent, quiet about private matters"
],
[
"dismayed",
"ML",
"adjective",
"upset, disheartened"
],
[
"dispel",
"ML",
"verb",
"to alleviate fears, to drive off"
],
[
"disperse",
"ML",
"verb",
"to send off, to dispel"
],
[
"dispute",
"ML",
"verb",
"to debate, argue"
],
[
"dissect",
"ML",
"verb",
"to cut apart, to analyze"
],
[
"distasteful",
"LL",
"adjective",
"unpleasant, offensive"
],
[
"distinguished",
"ML",
"adjective",
"known for excellence; noted, eminent, famous"
],
[
"distort",
"ML",
"verb",
"to twist out of shape, to misrepresent"
],
[
"distrust",
"ML",
"verb",
"to regard with doubt or suspicion; have no trust in"
],
[
"diversity",
"LL",
"noun",
"variety"
],
[
"divine",
"ML",
"adjective",
"heavenly, celestial"
],
[
"docile",
"ML",
"adjective",
"easily managed, calm"
],
[
"domestic",
"ML",
"adjective",
"relating to the household"
],
[
"dominate",
"LL",
"verb",
"to rule over, to govern"
],
[
"donate",
"LL",
"verb",
"give, contribute"
],
[
"dormant",
"ML",
"adjective",
"temporarily inactive, asleep"
],
[
"drastic",
"LL",
"adjective",
"extremely severe"
],
[
"dread",
"LL",
"verb",
"to fear greatly"
],
[
"dregs",
"ML",
"noun",
"the least valuable part of anything"
],
[
"drench",
"LL",
"verb",
"to wet thoroughly, soak"
],
[
"dubious",
"ML",
"adjective",
"doubtful"
],
[
"duration",
"LL",
"noun",
"the length of an event or experience"
],
[
"eager",
"LL",
"adjective",
"keen, longing for something"
],
[
"economize",
"ML",
"verb",
"to avoid waste or extravagance"
],
[
"edit",
"LL",
"verb",
"to revise or correct"
],
[
"elation",
"ML",
"noun",
"great joy or pride"
],
[
"elongate",
"LL",
"verb",
"to lengthen, to extend"
],
[
"eloquent",
"ML",
"adjective",
"fancy or appropriate in speech or expression"
],
[
"embodying",
"ML",
"verb",
"to give concrete form to, to provide with a body"
],
[
"emphasis",
"LL",
"noun",
"stress laid upon something, something that is given importance"
],
[
"enclose",
"LL",
"verb",
"to surround"
],
[
"encumber",
"ML",
"verb",
"to burden or weigh down"
],
[
"endeavor",
"ML",
"noun",
"an attempt; or, verb - to strive to accomplish something"
],
[
"engage",
"ML",
"verb",
"to attract and hold fast"
],
[
"entrust",
"LL",
"verb",
"to charge someone with a mission, a responsibility"
],
[
"envelop",
"ML",
"verb",
"to surround entirely"
],
[
"envy",
"LL",
"verb",
"to be jealous of someone or their position or possessions"
],
[
"equitable",
"ML",
"adjective",
"just and right, fair, reasonable"
],
[
"equity",
"ML",
"noun",
"something that is fair and just"
],
[
"equivalent",
"LL",
"adjective",
"equal to"
],
[
"erode",
"ML",
"verb",
"to eat into or away; destroy by slow disintegration"
],
[
"erratic",
"LL",
"adjective",
"eccentric, unpredictable"
],
[
"eternal",
"LL",
"adjective",
"without beginning or end; lasting forever"
],
[
"euphemism",
"ML",
"noun",
"the substitution of something more agreeable for something that is found to be offensive"
],
[
"evacuate",
"LL",
"verb",
"to vacate, to empty out"
],
[
"evade",
"ML",
"verb",
"to escape trickery or an enemy"
],
[
"excavate",
"ML",
"verb",
"to dig up"
],
[
"excel",
"ML",
"verb",
"to surpass someone in a subject or event"
],
[
"exclude",
"ML",
"verb",
"to shut or keep out"
],
[
"exemplify",
"ML",
"verb",
"to illustrate by example"
],
[
"exile",
"LL",
"verb",
"to be banished"
],
[
"exquisite",
"LL",
"adjective",
"beautifully designed"
],
[
"extend",
"LL",
"verb",
"to stretch or draw out"
],
[
"extinct",
"LL",
"adjective",
"no longer existing"
],
[
"extract",
"ML",
"verb",
"to get, pull, or draw out, usually with special effort, skill, or force"
],
[
"extravagant",
"LL",
"adjective",
"excessively fancy"
],
[
"exuberant",
"ML",
"adjective",
"extremely happy; overflowing, plentiful"
],
[
"facet",
"ML",
"noun",
"an aspect of something"
],
[
"falter",
"ML",
"verb",
"to stumble, pause, or to make a mistake"
],
[
"fanatic",
"ML",
"noun",
"a person with an extreme and uncritical enthusiasm or zeal"
],
[
"fathom",
"ML",
"verb",
"to comprehend, to measure the depth of"
],
[
"fatigue",
"ML",
"noun",
"weariness"
],
[
"favorable",
"ML",
"adjective",
"characterized by approval or support; positive"
],
[
"feasible",
"ML",
"adjective",
"capable of being achieved"
],
[
"feeble",
"LL",
"adjective",
"physically weak"
],
[
"feisty",
"LL",
"adjective",
"full of energy, spirited"
],
[
"fickle",
"ML",
"adjective",
"easily changed, mercurial"
],
[
"fission",
"ML",
"noun",
"splitting apart"
],
[
"fissure",
"ML",
"noun",
"a narrow opening, gap, or groove"
],
[
"flaccid",
"ML",
"adjective",
"soft, limp, flabby"
],
[
"flatter",
"LL",
"verb",
"to compliment"
],
[
"fleeting",
"LL",
"adjective",
"gone quickly; of a short length of time"
],
[
"flourish",
"LL",
"verb",
"to succeed with grace"
],
[
"foolhardy",
"ML",
"adjective",
"reckless, rash"
],
[
"foresee",
"ML",
"verb",
"to know in advance, to see beforehand"
],
[
"foreshorten",
"LL",
"verb",
"to abridge, reduce, or contract; make shorter"
],
[
"forge",
"ML",
"verb",
"to form by beating into shape, to make"
],
[
"forlorn",
"LL",
"adjective",
"lonely, sad"
],
[
"formulate",
"LL",
"verb",
"to express precisely, to devise"
],
[
"fortunate",
"LL",
"adjective",
"having good fortune, to have favor"
],
[
"foster",
"ML",
"verb",
"to promote, to shelter"
],
[
"fragile",
"LL",
"adjective",
"easily breakable, delicate"
],
[
"frank",
"LL",
"adjective",
"direct and unreserved in speech"
],
[
"frantic",
"LL",
"adjective",
"desperate or wild with excitement, passion, fear, or pain"
],
[
"frightful",
"LL",
"adjective",
"horrible, shocking, or revolting"
],
[
"frugal",
"LL",
"adjective",
"thrifty, not spending much money"
],
[
"fruitless",
"ML",
"adjective",
"useless, unproductive, without results or success"
],
[
"fundamental",
"ML",
"adjective",
"necessary, an essential part of"
],
[
"furious",
"LL",
"adjective",
"extremely mad, full of rage"
],
[
"fuse",
"ML",
"noun",
"a tube, cord, or the like, filled or saturated with combustible matter, for igniting an explosive"
],
[
"fusion",
"LL",
"noun",
"joining together, merging"
],
[
"genuine",
"LL",
"adjective",
"real, authentic"
],
[
"glean",
"ML",
"verb",
"to gather slowly, to reap"
],
[
"glint",
"LL",
"noun",
"a quick flash of light; a shining luster"
],
[
"glisten",
"LL",
"verb",
"to shine"
],
[
"glitch",
"ML",
"noun",
"a defect or malfunction in a machine or plan"
],
[
"graceful",
"LL",
"adjective",
"elegant in form, manner, movement, or speech"
],
[
"gratify",
"ML",
"verb",
"to give pleasure by satisfying desires"
],
[
"grave",
"ML",
"adjective",
"significantly serious"
],
[
"grievance",
"ML",
"noun",
"complaint, resentment"
],
[
"guarantee",
"ML",
"noun",
"a promise or assurance"
],
[
"gullible",
"ML",
"adjective",
"easily fooled"
],
[
"habitat",
"LL",
"noun",
"the natural environment of an organism"
],
[
"habitual",
"ML",
"adjective",
"commonly used, followed, observed, etc., as by a particular person; customary"
],
[
"haphazard",
"ML",
"adjective",
"unplanned, random, disorderly"
],
[
"hardship",
"LL",
"noun",
"a condition that is difficult to endure"
],
[
"hardy",
"ML",
"adjective",
"sturdy, strong"
],
[
"hasten",
"ML",
"verb",
"to move or act quickly"
],
[
"haughty",
"ML",
"adjective",
"proud, arrogant"
],
[
"hazard",
"LL",
"noun",
"caution or warning"
],
[
"heap",
"LL",
"noun",
"a group of things placed, thrown, or lying one on another; a pile"
],
[
"hectic",
"ML",
"adjective",
"intense agitation or excitement; confused and rapid movement"
],
[
"herald",
"LL",
"noun",
"a person or thing that proclaims or announces"
],
[
"hesitate",
"LL",
"verb",
"to pause, to reconsider"
],
[
"hinder",
"ML",
"verb",
"to delay, to prevent something from happening"
],
[
"hoard",
"LL",
"verb",
"to gather a large amount for future use"
],
[
"hoax",
"ML",
"noun",
"something intended to deceive or defraud"
],
[
"hoist",
"LL",
"verb",
"to raise or lift"
],
[
"homely",
"ML",
"adjective",
"not having elegance, unattractive"
],
[
"hoodwink",
"ML",
"verb",
"to deceive or trick"
],
[
"hovel",
"ML",
"noun",
"a shack"
],
[
"hubris",
"ML",
"noun",
"excessive pride"
],
[
"hypothesis",
"ML",
"noun",
"a mere assumption or guess"
],
[
"idealism",
"ML",
"noun",
"the pursuit of higher goals or standards"
],
[
"idiosyncrasy",
"ML",
"noun",
"a characteristic, habit, mannerism, or the like, that is peculiar to an individual"
],
[
"ignorant",
"LL",
"adjective",
"lacking in knowledge or training; unlearned"
],
[
"illuminate",
"LL",
"verb",
"to light up"
],
[
"illustrate",
"LL",
"verb",
"to furnish with drawings, to present ideas through pictures"
],
[
"immaculate",
"ML",
"adjective",
"perfectly clean"
],
[
"immediate",
"ML",
"adjective",
"occurring or accomplished without delay; instant"
],
[
"immunity",
"ML",
"noun",
"the state of being insusceptible to a particular disease or the like"
],
[
"impasse",
"ML",
"noun",
"a deadlock, standstill"
],
[
"impede",
"ML",
"verb",
"to slow in movement or progress by means of obstacles or hindrances; obstruct; hinder"
],
[
"imply",
"LL",
"verb",
"to express indirectly"
],
[
"impoverish",
"ML",
"verb",
"to make poor in quality or productiveness; to exhaust the strength or richness of"
],
[
"impulsive",
"ML",
"adjective",
"swayed by emotional influences"
],
[
"inane",
"ML",
"adjective",
"silly, empty"
],
[
"incentive",
"ML",
"noun",
"something that incites to action; serves as a reward offered for increased productivity"
],
[
"incident",
"LL",
"noun",
"an occurrence or event"
],
[
"incision",
"LL",
"noun",
"a cut or gash"
],
[
"incompetent",
"LL",
"adjective",
"unable to do something properly"
],
[
"indifferent",
"ML",
"adjective",
"without interest, not caring"
],
[
"infiltrate",
"ML",
"verb",
"to filter through"
],
[
"ingenious",
"ML",
"adjective",
"cleverly inventive or resourceful"
],
[
"inhabit",
"LL",
"verb",
"to live in, to exist within"
],
[
"initial",
"LL",
"adjective",
"the beginning of something, the first"
],
[
"initiate",
"ML",
"verb",
"to begin or originate"
],
[
"innate",
"ML",
"adjective",
"possessed at birth, not learned"
],
[
"innovate",
"ML",
"verb",
"to introduce something new"
],
[
"inquiry",
"LL",
"noun",
"a request for information"
],
[
"inscribe",
"LL",
"verb",
"to write or etch words into a surface"
],
[
"inscrutable",
"ML",
"adjective",
"not easily understood; mysterious; unfathomable"
],
[
"insight",
"LL",
"noun",
"understanding the true nature of something"
],
[
"instigate",
"ML",
"verb",
"to urge, provoke, or incite to some action or course"
],
[
"intangible",
"ML",
"adjective",
"not able to be touched or sensed"
],
[
"integrate",
"ML",
"verb",
"to make whole"
],
[
"integrity",
"LL",
"noun",
"applying moral principles, being ethical"
],
[
"intermission",
"LL",
"noun",
"a short interval between two events"
],
[
"intricate",
"LL",
"adjective",
"complex, having many detailed parts"
],
[
"invoke",
"ML",
"verb",
"to call on, to call for with desire"
],
[
"jeer",
"ML",
"verb",
"to make fun of"
],
[
"justify",
"ML",
"verb",
"to show to be fair and right"
],
[
"keen",
"ML",
"adjective",
"sharp, with an edge"
],
[
"kinetic",
"ML",
"adjective",
"moving"
],
[
"lament",
"ML",
"verb",
"to mourn"
],
[
"languid",
"ML",
"adjective",
"drooping, lacking energy"
],
[
"legislate",
"ML",
"verb",
"to make or enact laws"
],
[
"lethal",
"ML",
"adjective",
"causing death; deadly; fatal"
],
[
"liberate",
"LL",
"verb",
"to free"
],
[
"limber",
"ML",
"adjective",
"being lithe, flexible"
],
[
"linger",
"LL",
"verb",
"to remain or stay in a place longer than is usual or expected"
],
[
"listless",
"ML",
"adjective",
"having or showing little or no interest in anything; languid; spiritless; indifferent"
],
[
"loathe",
"ML",
"verb",
"to feel disgust or intense aversion for; to abhor"
],
[
"lodging",
"ML",
"noun",
"accommodation in a house, especially in rooms for rent"
],
[
"magnify",
"LL",
"verb",
"to increase the apparent size of, as a lens does"
],
[
"malignant",
"ML",
"adjective",
"very dangerous or harmful in influence or effect"
],
[
"mar",
"ML",
"verb",
"to spoil"
],
[
"meager",
"ML",
"adjective",
"lacking fullness, deficient"
],
[
"meander",
"ML",
"verb",
"to ramble, to continue on indirectly"
],
[
"meddle",
"LL",
"verb",
"to involve oneself without invitation"
],
[
"meditate",
"ML",
"verb",
"to engage in thought or contemplation; reflect"
],
[
"medley",
"ML",
"noun",
"a mixture, especially of heterogeneous elements"
],
[
"meek",
"ML",
"adjective",
"humbly patient or docile, as under provocation from others"
],
[
"memento",
"ML",
"noun",
"an object that serves to remind one of a person or past event"
],
[
"merciless",
"ML",
"adjective",
"having or showing no mercy; pitiless; cruel"
],
[
"merge",
"LL",
"verb",
"to join two things together"
],
[
"meticulous",
"ML",
"adjective",
"careful, attention paid to detail"
],
[
"mischievous",
"ML",
"adjective",
"maliciously or playfully annoying"
],
[
"moderate",
"ML",
"adjective",
"not extreme, excessive, or intense"
],
[
"modify",
"LL",
"verb",
"to change the form of, to alter"
],
[
"molten",
"LL",
"adjective",
"melted, liquefied by heat"
],
[
"momentous",
"ML",
"adjective",
"of great or far-reaching importance or consequence"
],
[
"mope",
"ML",
"verb",
"to be sunk in dejection or listless apathy; sulk; brood"
],
[
"muddle",
"ML",
"verb",
"to mix up, to jumble"
],
[
"mundane",
"ML",
"adjective",
"common, ordinary"
],
[
"mute",
"ML",
"adjective",
"silent; refraining from speech or utterance"
],
[
"negate",
"ML",
"verb",
"to deny the existence of, to nullify"
],
[
"noncommittal",
"ML",
"adjective",
"without commitment"
],
[
"nostalgic",
"LL",
"adjective",
"experiencing memories/happy feelings of the past"
],
[
"notorious",
"ML",
"adjective",
"known widely, often unfavorably"
],
[
"novice",
"LL",
"noun",
"a beginner"
],
[
"noxious",
"ML",
"adjective",
"harmful to one's well-being"
],
[
"null",
"ML",
"adjective",
"void, zero value"
],
[
"obedient",
"LL",
"adjective",
"obeying or willing to obey; complying with or submissive to authority"
],
[
"objective",
"LL",
"noun",
"something that one's efforts or actions are intended to attain or accomplish; purpose; goal; target"
],
[
"obscure",
"ML",
"adjective",
"hidden by something, covered"
],
[
"obstruct",
"ML",
"verb",
"to block, to stall"
],
[
"occupation",
"ML",
"noun",
"a person's usual or principal work or business, especially as a means of earning a living; vocation"
],
[
"occupy",
"LL",
"verb",
"to take up space"
],
[
"ominous",
"ML",
"adjective",
"threatening future bad events"
],
[
"omit",
"ML",
"verb",
"to take out, to keep out"
],
[
"optimistic",
"LL",
"adjective",
"to keep high hopes for, to remain positive"
],
[
"overbearing",
"LL",
"adjective",
"domineering, arrogant"
],
[
"overt",
"ML",
"adjective",
"open to knowledge, not secret"
],
[
"overwhelm",
"ML",
"verb",
"to overcome completely in mind or feeling"
],
[
"pacify",
"ML",
"verb",
"to restore to a peaceful state"
],
[
"pact",
"LL",
"noun",
"a formal agreement"
],
[
"palpable",
"ML",
"adjective",
"readily seen, obvious, evident"
],
[
"paltry",
"ML",
"adjective",
"worthless, ridiculously small"
],
[
"parody",
"LL",
"noun",
"a humorous imitation"
],
[
"partial",
"LL",
"adjective",
"incomplete; not total"
],
[
"particle",
"LL",
"noun",
"a small fraction of something, a small amount"
],
[
"partisan",
"ML",
"adjective",
"partial to a specific person because of allegiance"
],
[
"patron",
"LL",
"noun",
"a client or someone who supports with money or gifts"
],
[
"pedestrian",
"ML",
"noun",
"a person who travels on foot; something that is commonplace"
],
[
"permeate",
"ML",
"verb",
"to pass through, to penetrate"
],
[
"perplexed",
"LL",
"adjective",
"bewildered, confused"
],
[
"persecute",
"ML",
"verb",
"to pursue with harassment, especially based on bias"
],
[
"personify",
"LL",
"verb",
"to represent in the form of a person, as in art"
],
[
"perspective",
"LL",
"noun",
"a person's perception of ideas or events"
],
[
"pervasive",
"ML",
"adjective",
"spread throughout"
],
[
"pessimistic",
"LL",
"adjective",
"to remain negative, to mainly have sad thoughts or ideas"
],
[
"philanthropy",
"ML",
"noun",
"an organization devoted to helping needy persons or to other socially useful purposes"
],
[
"pigment",
"LL",
"noun",
"a color, like a paint or ink"
],
[
"pilfer",
"ML",
"verb",
"to steal"
],
[
"pinnacle",
"LL",
"noun",
"a high peak, a point of great success or power"
],
[
"pious",
"ML",
"adjective",
"deeply religious"
],
[
"placate",
"ML",
"verb",
"to quiet down"
],
[
"plausible",
"LL",
"adjective",
"realistic, something that could have happened"
],
[
"plight",
"ML",
"noun",
"an unfortunate situation"
],
[
"pompous",
"ML",
"adjective",
"arrogant, haughty"
],
[
"porous",
"ML",
"adjective",
"permeable, possible to filter through"
],
[
"practical",
"ML",
"adjective",
"adapted or designed for actual use; useful"
],
[
"precede",
"ML",
"verb",
"to go before, as in place, order, rank, importance, or time"
],
[
"preclude",
"ML",
"verb",
"to prevent the presence or existence of; make impossible"
],
[
"precocious",
"ML",
"adjective",
"unusually advanced or mature in development, especially mental development"
],
[
"prediction",
"LL",
"noun",
"a hypothesis made for the future"
],
[
"prejudiced",
"LL",
"adjective",
"an opinion formed without knowledge or reason of the situation"
],
[
"preserve",
"LL",
"verb",
"to keep safe from harm or injury; to protect or spare"
],
[
"presume",
"ML",
"verb",
"to take for granted, to assume"
],
[
"pretentious",
"ML",
"adjective",
"ostentatious, arrogant"
],
[
"priceless",
"ML",
"adjective",
"invaluable"
],
[
"pristine",
"ML",
"adjective",
"extremely clean, in perfect condition"
],
[
"probable",
"ML",
"adjective",
"likely to occur or prove true"
],
[
"proclaim",
"ML",
"verb",
"to announce or declare in an official or formal manner"
],
[
"profane",
"ML",
"verb",
"to abuse or put to ill use; or, adjective - something that is considered offensive or inappropriate"
],
[
"prolific",
"ML",
"adjective",
"fertile, very productive"
],
[
"prominent",
"ML",
"adjective",
"conspicuous, noticeable"
],
[
"prone",
"ML",
"adjective",
"having a tendency towards something"
],
[
"prophecy",
"LL",
"noun",
"a prediction"
],
[
"prototype",
"ML",
"noun",
"a model of an original item"
],
[
"provoke",
"LL",
"verb",
"to anger or arouse to do something"
],
[
"pugnacious",
"ML",
"adjective",
"hostile, combative"
],
[
"pungent",
"LL",
"adjective",
"acutely distressing, sharply affecting smell"
],
[
"quake",
"ML",
"verb",
"to shake or tremble from cold, weakness, fear or anger"
],
[
"quash",
"ML",
"verb",
"to put down or suppress completely; quell; subdue"
],
[
"quell",
"ML",
"verb",
"to suppress; put an end to; extinguish"
],
[
"quiver",
"LL",
"verb",
"to tremble; or, noun - a container for arrows"
],
[
"rash",
"ML",
"adjective",
"acting or tending to act too hastily or without due consideration"
],
[
"ratify",
"ML",
"verb",
"to approve"
],
[
"ravenous",
"LL",
"adjective",
"extremely hungry"
],
[
"react",
"ML",
"verb",
"to act in response to an agent or influence"
],
[
"recoil",
"LL",
"verb",
"to draw back as in alarm, horror, or disgust"
],
[
"reflex",
"ML",
"noun",
"any automatic, unthinking, often habitual behavior or response"
],
[
"refute",
"ML",
"verb",
"to prove to be false or incorrect"
],
[
"relentless",
"LL",
"adjective",
"unyieldingly severe, strict, or harsh; unrelenting"
],
[
"reluctant",
"LL",
"adjective",
"unwilling, hesitant"
],
[
"reminisce",
"LL",
"verb",
"to remember fondly"
],
[
"remote",
"LL",
"adjective",
"far away, distant"
],
[
"renaissance",
"ML",
"noun",
"rebirth; revival; a renewal of life"
],
[
"rendezvous",
"ML",
"noun",
"a meeting, usually kept secret"
],
[
"rendition",
"LL",
"noun",
"an interpretation, as of a role or a piece of music"
],
[
"renounce",
"ML",
"verb",
"to give up"
],
[
"renown",
"ML",
"noun",
"having widespread and high repute; fame"
],
[
"replenish",
"LL",
"verb",
"to refill resources"
],
[
"repress",
"ML",
"verb",
"to hold in, to keep inside"
],
[
"reprimand",
"ML",
"verb",
"to rebuke or criticize"
],
[
"reproach",
"ML",
"verb",
"to find fault with, to blame"
],
[
"residual",
"ML",
"adjective",
"remaining"
],
[
"resolve",
"ML",
"verb",
"to come to a definite or earnest decision about; to determine"
],
[
"restore",
"LL",
"verb",
"to bring back to a former, original, or normal condition"
],
[
"restraint",
"ML",
"noun",
"the act of holding back, controlling, or checking"
],
[
"retort",
"ML",
"verb",
"to reply to, usually in a sharp or retaliatory way"
],
[
"revere",
"ML",
"verb",
"to regard with awe, venerate"
],
[
"revert",
"ML",
"verb",
"to return to a former habit or condition"
],
[
"rickety",
"ML",
"adjective",
"likely to fall or collapse; shaky"
],
[
"righteous",
"ML",
"adjective",
"morally right or justifiable"
],
[
"rigid",
"ML",
"adjective",
"stiff or unyielding; not pliant or flexible; hard"
],
[
"robust",
"ML",
"adjective",
"healthy, full in form"
],
[
"rouse",
"LL",
"verb",
"to bring out of a state of sleep or inactivity"
],
[
"rue",
"ML",
"verb",
"to regret"
],
[
"ruminate",
"ML",
"verb",
"to meditate or ponder"
],
[
"rustic",
"LL",
"adjective",
"relating to rural areas or the way of living in rural areas"
],
[
"ruthless",
"LL",
"adjective",
"without compassion, cruel/merciless"
],
[
"sacred",
"LL",
"adjective",
"devoted or dedicated to a deity or to some religious purpose"
],
[
"sage",
"LL",
"noun",
"a profoundly wise person; a person famed for wisdom"
],
[
"salvage",
"LL",
"verb",
"to save something from wreckage"
],
[
"satire",
"ML",
"noun",
"a parody, to make light of something"
],
[
"savor",
"LL",
"verb",
"to cherish, especially in regards to sweet smells or tastes"
],
[
"scant",
"ML",
"adjective",
"barely sufficient, not abundant"
],
[
"scarce",
"LL",
"adjective",
"a very limited supply"
],
[
"scrutinize",
"ML",
"verb",
"to examine in detail with careful or critical attention"
],
[
"scurry",
"ML",
"verb",
"to go or move quickly or in haste"
],
[
"seclude",
"ML",
"verb",
"to place in solitude, to isolate"
],
[
"secure",
"ML",
"adjective",
"free from or not exposed to danger or harm; safe"
],
[
"sedate",
"ML",
"verb",
"to calm, usually by way of drugs"
],
[
"seize",
"ML",
"verb",
"to take hold of suddenly or forcibly; to grasp"
],
[
"seldom",
"LL",
"adjective",
"on few occasions, infrequently"
],
[
"serene",
"LL",
"adjective",
"calm, peaceful, or tranquil; unruffled"
],
[
"severity",
"ML",
"noun",
"harshness, sternness, or rigor"
],
[
"shrewd",
"LL",
"adjective",
"astute, sharp in practical matters"
],
[
"simulate",
"LL",
"verb",
"to make a pretense of; to fake"
],
[
"sincere",
"ML",
"adjective",
"genuine, real"
],
[
"sinister",
"LL",
"adjective",
"threatening, harmful"
],
[
"solemn",
"ML",
"adjective",
"grave, sober, somber"
],
[
"solitary",
"LL",
"adjective",
"alone, individual"
],
[
"somber",
"ML",
"adjective",
"serious, dark"
],
[
"soothe",
"LL",
"verb",
"to calm, to comfort"
],
[
"specter",
"ML",
"noun",
"some object or source of terror or dread"
],
[
"spontaneous",
"ML",
"adjective",
"coming from a natural impulse, without premeditation"
],
[
"stagnate",
"ML",
"verb",
"to cease to flow; to become stale"
],
[
"stature",
"LL",
"noun",
"the height of any person or object"
],
[
"steadfast",
"LL",
"adjective",
"fixed in direction, resolute"
],
[
"stifle",
"ML",
"verb",
"to suppress, curb, or withhold"
],
[
"subjective",
"ML",
"adjective",
"influenced by personal opinion"
],
[
"subside",
"ML",
"verb",
"to become less active; to decrease in intensity"
],
[
"subtle",
"ML",
"adjective",
"delicate, faint, mysterious"
],
[
"succinct",
"ML",
"adjective",
"concise, having verbal brevity"
],
[
"sullen",
"ML",
"adjective",
"showing irritation or ill humor by a gloomy silence"
],
[
"sullied",
"ML",
"adjective",
"soiled, stained, tarnished"
],
[
"surly",
"ML",
"adjective",
"unfriendly or hostile; menacingly irritable"
],
[
"surrogate",
"ML",
"noun",
"a substitute; a temporary replacement"
],
[
"sympathize",
"ML",
"verb",
"to feel a compassion, as for suffering or trouble"
],
[
"synchronize",
"LL",
"verb",
"to operate, work, etc., at the same rate and exactly together"
],
[
"tact",
"ML",
"noun",
"a keen sense of what is appropriate, tasteful"
],
[
"tangible",
"ML",
"adjective",
"capable of being touched; real; actual"
],
[
"taper",
"ML",
"verb",
"to become smaller or thinner towards one end"
],
[
"task",
"LL",
"noun",
"any piece of work"
],
[
"tattered",
"ML",
"adjective",
"torn or worn to rags"
],
[
"taunt",
"LL",
"verb",
"to tease, to make fun of"
],
[
"temperament",
"ML",
"noun",
"mood or behavior"
],
[
"terse",
"ML",
"adjective",
"concise, curt"
],
[
"thorough",
"ML",
"adjective",
"extremely attentive to accuracy and detail"
],
[
"thrive",
"LL",
"verb",
"to prosper, to be successful"
],
[
"thwart",
"ML",
"verb",
"to prevent, to frustrate"
],
[
"timid",
"LL",
"adjective",
"shy, quiet"
],
[
"tiresome",
"LL",
"adjective",
"causing someone to become weary"
],
[
"toil",
"LL",
"verb",
"to work hard"
],
[
"torment",
"LL",
"noun",
"suffering, pain"
],
[
"treacherous",
"ML",
"adjective",
"dangerous, hazardous"
],
[
"trifle",
"ML",
"noun",
"a small thing of little value"
],
[
"trite",
"ML",
"adjective",
"lacking in freshness, stale; not creative or original"
],
[
"truce",
"LL",
"noun",
"an agreement or treaty"
],
[
"ultimate",
"LL",
"adjective",
"last, furthest, the maximum amount"
],
[
"uncouth",
"ML",
"adjective",
"awkward, clumsy"
],
[
"undermine",
"LL",
"verb",
"to bring down, to discourage"
],
[
"unique",
"LL",
"adjective",
"single, solitary in type or characteristics"
],
[
"unruly",
"LL",
"adjective",
"messy, lawless, turbulent"
],
[
"unusual",
"LL",
"adjective",
"not typical, common, or ordinary"
],
[
"uproot",
"ML",
"verb",
"to pull out as if by the roots"
],
[
"utilitarian",
"ML",
"adjective",
"purposeful, useful"
],
[
"utilize",
"ML",
"verb",
"to put to use"
],
[
"vacillate",
"ML",
"verb",
"to waver, sway, or stagger"
],
[
"vanity",
"ML",
"noun",
"excessive pride in one's appearance, qualities, abilities, achievements"
],
[
"variable",
"ML",
"adjective",
"capable of being changed; alterable"
],
[
"vast",
"ML",
"adjective",
"of very great size or proportions; huge; enormous"
],
[
"vend",
"ML",
"verb",
"to sell"
],
[
"versatile",
"ML",
"adjective",
"capable of having many uses"
],
[
"viewpoint",
"LL",
"noun",
"a point of observation, an attitude"
],
[
"vigilant",
"ML",
"adjective",
"watchful"
],
[
"vigorous",
"ML",
"adjective",
"with great energy"
],
[
"visible",
"ML",
"adjective",
"can be seen; perceptible to the eye"
],
[
"vivacious",
"ML",
"adjective",
"full of life"
],
[
"vivid",
"LL",
"adjective",
"descriptive, colorful"
],
[
"warble",
"LL",
"verb",
"to sing or whistle with trills, quavers, or melodic embellishments"
],
[
"weary",
"LL",
"adjective",
"tired"
],
[
"wily",
"ML",
"adjective",
"crafty, cunning"
],
[
"woeful",
"ML",
"adjective",
"wretched, unhappy"
],
[
"worthy",
"ML",
"adjective",
"of commendable excellence or merit; deserving"
],
[
"wrath",
"ML",
"noun",
"strong and stern anger"
],
[
"writhe",
"ML",
"verb",
"to twist, usually in sadness or anger"
],
[
"yield",
"LL",
"verb",
"to give up or surrender"
],
[
"zany",
"LL",
"adjective",
"whimsical, clownish"
]
];
